export const diseases = [
  { name: "Fungal infection", solutions: ["Eat Yoghurt and Probiotics: Yoghurt and other probiotics have an ample amount of good bacteria that help stave off many fungal infections. These fight off microbes that cause these infections. ","Wash with Soap and Water: Clean the affected area with soap/dettol and water twice daily before you apply any home remedies or any other medication. This will control the spread of infection.","Use Apple Cider Vinegar: Apple cider vinegar has antifungal properties. You could mix two tablespoons in warm water and drink it up or dip a cotton ball in it and dab over your skin. Doing this thrice a day should produce beneficial results."] },
  { name: "Allergy", solutions: ["Use a Saline nasal irrigation to clean up the nasal airway.","By removing moisture from the air, air conditioners and dehumidifiers can limit the growth of mildew and mold that can negatively impact allergies.","Ginger suppressed the production of pro-inflammatory proteins in the blood of mice, which led to reduced allergy symptoms."] },
  { name: "GERD", solutions: ["Raise the head of the bed,Eat a healthy anti-inflammatory diet ","Try smaller meals and avoid eating late.","Monitor trigger foods and avoid them."] },
  { name: "Chronic cholestasis", solutions: ["Guar Gum: Guar gum is a fiber from the seed of the guar plant. It’s commonly used as a laxative, for reducing cholesterol and preventing diabetes and obesity.","Activated Charcoal:Activated charcoal is a potent natural treatment that’s used to trap toxins and chemicals in the body, allowing them to be flushed out before they’re absorbed. ","Milk Thistle: Milk thistle is a natural herb that’s commonly used to detoxify the body, especially the liver. It’s able to promote healthy digestive function by increasing bile production and decreasing inflammation.","Dandelion Root: Dandelion root and dandelion tea are safe natural remedies for cholestasisand have been proven to strengthen and benefit the liver."] },
  { name: "Drug Reaction", solutions: ["Discontinue the use of the drug. ","medication detoxification can be aided by re-hydrating your body,Drinking adequate water during the day acts as a natural detox and can help flush the body of chemicals, toxins, and fats. ","Consult a Doctor if symptoms Persist "] },
  { name: "Peptic ulcer diseae", solutions: ["Cabbage is a popular natural ulcer remedy.It’s rich in vitamin C, an antioxidant shown to help prevent and treat H. pylori infections. These infections are the most common cause of stomach ulcers","Honey is an antioxidant-rich food which can prevent the formation and promote the healing of many wounds, including ulcers","garlic extracts may speed up recovery from ulcers and even reduce the likelihood of them developing in the first place","Turmeric polysaccharides can alleviate gastric ulcers by protecting the mucus lining of stomach and inhibiting the growth of an ulcer-causing bacteria."] },
  { name: "AIDS", solutions: ["Yoga and massage therapy may help reduce pain for some people. ","Marijuana can help reduce pain, control nausea, and increase appetite. ","Avoid garlic as Garlic supplements can make certain HIV treatments much less effective. "] },
  { name: "Diabetes ", solutions: ["Apple Cider Vinegar:Taking 2 tablespoons before bedtime can reduce your morning fasting sugar levels.Even better, 1-2 tablespoons of ACV taken with meals can decrease the glycemic load of a carbohydrate rich meal ","Increase Fibre Intake: It has been proven though many studies that foods which have high fibre content slow down the release of glucose from food. Whole fruit, vegetables and beans are examples of such foods ","Chromium:Mainly found in brewer’s yeast, deficiency in chromium impairs the metabolism of glucose.Be careful if you have kidney disease with this supplement. ","Aloe Vera:The sap of aloe vera is known for its laxative effect.Therefore, make sure to get the juice of the gel! There is increasing evidence for use of the gel, which is the mucilaginous material inside the leaves.","Regular Exercise:  Exercising regularly can help increase the insulin sensitivity in your body. "] },
  { name: "Gastroenteritis", solutions: [] },
  { name: "Bronchial Asthma", solutions: [] },
  { name: "Hypertension ", solutions: [] },
  { name: "Migraine", solutions: [] },
  { name: "Cervical spondylosis", solutions: [] },
  { name: "Paralysis (brain hemorrhage)", solutions: [] },
  { name: "Jaundice", solutions: [] },
  { name: "Malaria", solutions: [] },
  { name: "Chicken pox", solutions: [] },
  { name: "Dengue", solutions: [] },
  { name: "Typhoid", solutions: [] },
  { name: "hepatitis A", solutions: [] },
  { name: "Hepatitis B", solutions: [] },
  { name: "Hepatitis C", solutions: [] },
  { name: "Hepatitis D", solutions: [] },
  { name: "Hepatitis E", solutions: [] },
  { name: "Alcoholic hepatitis", solutions: [] },
  { name: "Tuberculosis", solutions: [] },
  { name: "Common Cold", solutions: [] },
  { name: "Pneumonia", solutions: [] },
  { name: "Dimorphic hemmorhoids(piles)", solutions: [] },
  { name: "Heart attack", solutions: ["Garlic:Garlic's been used for centuries to boost heart health as well as other things. ","Eating a non-inflammatory diet or a DASH diet can improve heart health. ","Avoid chemically-modified foods and high sugar foods. ","Avoid excessive consumption of red meat and fatty foods","Reduce your stress levels. "] },
  { name: "Varicose veins", solutions: [] },
  { name: "Hypothyroidism", solutions: [] },
  { name: "Hyperthyroidism", solutions: [] },
  { name: "Hypoglycemia", solutions: ["Consuming high-sugar foods or drinks can treat this condition.",] },
  { name: "Osteoarthristis", solutions: [] },
  { name: "Arthritis", solutions: [] },
  { name: "(vertigo) Paroymsal  Positional Vertigo", solutions: [] },
  { name: "Acne", solutions: [] },
  { name: "Urinary tract infection", solutions: [] },
  { name: "Psoriasis", solutions: [] },
  { name: "Impetigo", solutions: [] },
  {name:"Sinusitis",solutions:["Nasal Washing using salt and warm water", "Use steam to heat up your face","Use Netipot to rinse debris from your nasal cavity","Accupressure: Gently massage your sinus area to improve bloodflow"]}
];
