export const diseases = [
  { name: "Fungal infection", solutions: [] },
  { name: "Allergy", solutions: [] },
  { name: "GERD", solutions: [] },
  { name: "Chronic cholestasis", solutions: [] },
  { name: "Drug Reaction", solutions: [] },
  { name: "Peptic ulcer diseae", solutions: [] },
  { name: "AIDS", solutions: [] },
  { name: "Diabetes ", solutions: [] },
  { name: "Gastroenteritis", solutions: [] },
  { name: "Bronchial Asthma", solutions: [] },
  { name: "Hypertension ", solutions: [] },
  { name: "Migraine", solutions: [] },
  { name: "Cervical spondylosis", solutions: [] },
  { name: "Paralysis (brain hemorrhage)", solutions: [] },
  { name: "Jaundice", solutions: [] },
  { name: "Malaria", solutions: [] },
  { name: "Chicken pox", solutions: [] },
  { name: "Dengue", solutions: [] },
  { name: "Typhoid", solutions: [] },
  { name: "hepatitis A", solutions: [] },
  { name: "Hepatitis B", solutions: [] },
  { name: "Hepatitis C", solutions: [] },
  { name: "Hepatitis D", solutions: [] },
  { name: "Hepatitis E", solutions: [] },
  { name: "Alcoholic hepatitis", solutions: [] },
  { name: "Tuberculosis", solutions: [] },
  { name: "Common Cold", solutions: [] },
  { name: "Pneumonia", solutions: [] },
  { name: "Dimorphic hemmorhoids(piles)", solutions: [] },
  { name: "Heart attack", solutions: [] },
  { name: "Varicose veins", solutions: [] },
  { name: "Hypothyroidism", solutions: [] },
  { name: "Hyperthyroidism", solutions: [] },
  { name: "Hypoglycemia", solutions: [] },
  { name: "Osteoarthristis", solutions: [] },
  { name: "Arthritis", solutions: [] },
  { name: "(vertigo) Paroymsal  Positional Vertigo", solutions: [] },
  { name: "Acne", solutions: [] },
  { name: "Urinary tract infection", solutions: [] },
  { name: "Psoriasis", solutions: [] },
  { name: "Impetigo", solutions: [] },
  {name:"Sinusitis",solutions:["Nasal Washing using salt and warm water", "Use steam to heat up your face","Use Netipot to rinse debris from your nasal cavity","Accupressure: Gently massage your sinus area to improve bloodflow"]}
];
