export const diseases = [
  { name: "Fungal infection", solutions: ["Eat Yoghurt and Probiotics: Yoghurt and other probiotics have an ample amount of good bacteria that help stave off many fungal infections. These fight off microbes that cause these infections. ","Wash with Soap and Water: Clean the affected area with soap/dettol and water twice daily before you apply any home remedies or any other medication. This will control the spread of infection.","Use Apple Cider Vinegar: Apple cider vinegar has antifungal properties. You could mix two tablespoons in warm water and drink it up or dip a cotton ball in it and dab over your skin. Doing this thrice a day should produce beneficial results."] },
  { name: "Allergy", solutions: ["Use a Saline nasal irrigation to clean up the nasal airway.","By removing moisture from the air, air conditioners and dehumidifiers can limit the growth of mildew and mold that can negatively impact allergies.","Ginger suppressed the production of pro-inflammatory proteins in the blood of mice, which led to reduced allergy symptoms."] },
  { name: "GERD", solutions: ["Raise the head of the bed,Eat a healthy anti-inflammatory diet ","Try smaller meals and avoid eating late.","Monitor trigger foods and avoid them."] },
  { name: "Chronic cholestasis", solutions: ["Guar Gum: Guar gum is a fiber from the seed of the guar plant. It’s commonly used as a laxative, for reducing cholesterol and preventing diabetes and obesity.","Activated Charcoal:Activated charcoal is a potent natural treatment that’s used to trap toxins and chemicals in the body, allowing them to be flushed out before they’re absorbed. ","Milk Thistle: Milk thistle is a natural herb that’s commonly used to detoxify the body, especially the liver. It’s able to promote healthy digestive function by increasing bile production and decreasing inflammation.","Dandelion Root: Dandelion root and dandelion tea are safe natural remedies for cholestasisand have been proven to strengthen and benefit the liver."] },
  { name: "Drug Reaction", solutions: ["Discontinue the use of the drug. ","medication detoxification can be aided by re-hydrating your body,Drinking adequate water during the day acts as a natural detox and can help flush the body of chemicals, toxins, and fats. ","Consult a Doctor if symptoms Persist "] },
  { name: "Peptic ulcer diseae", solutions: ["Cabbage is a popular natural ulcer remedy.It’s rich in vitamin C, an antioxidant shown to help prevent and treat H. pylori infections. These infections are the most common cause of stomach ulcers","Honey is an antioxidant-rich food which can prevent the formation and promote the healing of many wounds, including ulcers","garlic extracts may speed up recovery from ulcers and even reduce the likelihood of them developing in the first place","Turmeric polysaccharides can alleviate gastric ulcers by protecting the mucus lining of stomach and inhibiting the growth of an ulcer-causing bacteria."] },
  { name: "AIDS", solutions: ["Yoga and massage therapy may help reduce pain for some people. ","Marijuana can help reduce pain, control nausea, and increase appetite. ","Avoid garlic as Garlic supplements can make certain HIV treatments much less effective. "] },
  { name: "Diabetes ", solutions: ["Apple Cider Vinegar:Taking 2 tablespoons before bedtime can reduce your morning fasting sugar levels.Even better, 1-2 tablespoons of ACV taken with meals can decrease the glycemic load of a carbohydrate rich meal ","Increase Fibre Intake: It has been proven though many studies that foods which have high fibre content slow down the release of glucose from food. Whole fruit, vegetables and beans are examples of such foods ","Chromium:Mainly found in brewer’s yeast, deficiency in chromium impairs the metabolism of glucose.Be careful if you have kidney disease with this supplement. ","Aloe Vera:The sap of aloe vera is known for its laxative effect.Therefore, make sure to get the juice of the gel! There is increasing evidence for use of the gel, which is the mucilaginous material inside the leaves.","Regular Exercise:  Exercising regularly can help increase the insulin sensitivity in your body. "] },
  { name: "Gastroenteritis", solutions: [] },
  { name: "Bronchial Asthma", solutions: [] },
  { name: "Hypertension ", solutions: [] },
  { name: "Migraine", solutions: [] },
  { name: "Cervical spondylosis", solutions: [] },
  { name: "Paralysis (brain hemorrhage)", solutions: [] },
  { name: "Jaundice", solutions: [] },
  { name: "Malaria", solutions: [] },
  { name: "Chicken pox", solutions: [] },
  { name: "Dengue", solutions: [] },
  { name: "Typhoid", solutions: [] },
  { name: "hepatitis A", solutions: [] },
  { name: "Hepatitis B", solutions: [] },
  { name: "Hepatitis C", solutions: [] },
  { name: "Hepatitis D", solutions: [] },
  { name: "Hepatitis E", solutions: [] },
  { name: "Alcoholic hepatitis", solutions: [] },
  { name: "Tuberculosis", solutions: [] },
  { name: "Common Cold", solutions: [] },
  { name: "Pneumonia", solutions: [] },
  { name: "Dimorphic hemmorhoids(piles)", solutions: [] },
  { name: "Heart attack", solutions: ["Garlic:Garlic's been used for centuries to boost heart health as well as other things. ","Eating a non-inflammatory diet or a DASH diet can improve heart health. ","Avoid chemically-modified foods and high sugar foods. ","Avoid excessive consumption of red meat and fatty foods","Reduce your stress levels. "] },
  { name: "Varicose veins", solutions: ["Eating Berries help as it contains antioxidants that can help to reduce inflammation and can help to strengthen your veins",
"Regular exercise encourages better blood circulation in the legs, which helps to push along the blood that has collected in the veins.",
"Adding foods like  onions, bell peppers, spinach, and broccoli that contain flavonoids may also help a person to shrink their varicose veins.Flavonoids improve blood circulation",
"Taking grape seed extract, Vitis vinifera, orally may help to reduce swelling in the lower legs and other symptoms of chronic venous insufficiency.",
"Gently massaging the affected areas with massaging Oil can help to keep the blood moving through the veins",] },
  { name: "Hypothyroidism", solutions: [] },
  { name: "Hyperthyroidism", solutions: ["avoid eating excessive amounts of iodine-rich foods",
"cruciferous vegetables contain compounds that decrease thyroid hormone production and may reduce iodine uptake by the thyroid.",
"hypothyroidism and small intestine problems are linked.Probiotic supplements contain live helpful bacteria that can help keep your stomach and intestines healthy.",
"Coconut oil has medium-chain fatty acids that help in better functioning of the thyroid gland.",
"take Vitamin B and D.Vitamins help to fight the underlying causes of thyroid problems. ",] },
  { name: "Hypoglycemia", solutions: ["Consuming high-sugar foods or drinks can treat this condition.",] },
  { name: "Osteoarthristis", solutions: ["When it comes to pain, hot and cold compresses may be very beneficial.",
"Epsom salt baths can provide allover relief, especially for joint pain. The magnesium in Epsom salt may help with inflammation and pain.",
"Green tea contains polyphenols. These compounds may help reduce inflammation and the need for medications.",
"Turmeric (curcumin) Treats inflammation, pain, and stiffness",
"sugar,salt, Saturated Fat and Trans Fats are associated with increased inflammation and should be limited for people who have osteoarthritis.",] },
  { name: "Arthritis", solutions: ["Avoid Processed foods, salt, red meat, alcohol, and other foods as these may exacerbate arthritis' joint pain and inflammation.",
"Stick to low-calorie whole foods with lots of vitamins and fiber, like leafy greens and beans.",
"Exercised like cycling, daily walks can help avoid the symptoms",
"Heat treatments can include taking a long, warm shower or bath in the morning to help ease stiffness ",] },
  { name: "(vertigo) Paroymsal  Positional Vertigo", solutions: [] },
  { name: "Acne", solutions: ["Tea tree oil’s anti-inflammatory properties mean that it can also reduce the swelling and redness of pimples.",
"Aloe vera is a natural antibacterial and anti-inflammatory, meaning it may reduce the appearance of acne and prevent acne breakouts.",
"Honey: Using a clean finger or cotton pad, rub a little honey into pimples. Otherwise, add honey to a face or body mask.",] },
  { name: "Urinary tract infection", solutions: ["Drinking unsweetened cranberry juice may help,as it is an ingredient that stops bacteria from attaching to the walls of the urinary tract.",
"Drink plenty of Fluids as Hydration status has been linked to the risk of urinary tract infection.",
"Increasing your intake of vitamin C could protect against urinary tract infections.",
"it’s important not to hold urine for too long. This can lead to a buildup of bacteria, resulting in infection",] },
  { name: "Psoriasis", solutions: ["Dietary supplements like Fish oil, vitamin D, milk thistle, aloe vera, Oregon grape, and evening primrose oil have all been reported to help ease mild symptoms of Psoriasis.",
"Aloe vera has been shown in some cases to reduce redness and irritation caused by psoriasis.",
"Avoiding  red meat, saturated fats, refined sugars, carbohydrates, and alcohol may help reduce flare-ups triggered by such foods.",
"A lukewarm bath with Epsom salt, mineral oil, milk, or olive oil can soothe the itching and infiltrate scales and plaques. Oatmeal baths can also be very helpful and soothing for plaque psoriasis.",
"Reduce stress whenever possible, consider incorporating stress-reducing practices such as yoga and meditation.",] },
  { name: "Impetigo", solutions: ["Apply Aloe vera (Aloe barbadensis) to the affected area.",
"Make chamomile tea and use it as a skin wash. Or apply a used, cooled chamomile tea bag directly on sores.",
"Place the cut side of a slice of garlic directly on impetigo sores. This may sting a little. You can also press garlic cloves, and then apply topically. ",
"it is also great to incorporate Garlic to your diet.",
"Maintain a healthy weight and Manage your cholesterol.",] },
  {name:"Sinusitis",solutions:["Nasal Washing using salt and warm water", "Use steam to heat up your face","Use Netipot to rinse debris from your nasal cavity","Accupressure: Gently massage your sinus area to improve bloodflow"]}
];
