export const symptoms = [
  "itching",
  "skin_rash",
  "nodal_skin_eruptions",
  "continuous_sneezing",
  "shivering",
  "chills",
  "joint_pain",
  "stomach_pain",
  "acidity",
  "ulcers_on_tongue",
  "muscle_wasting",
  "vomiting",
  "burning_micturition",
  "spotting_",
  "urination",
  "fatigue",
  "weight_gain",
  "anxiety",
  "cold_hands_and_feets",
  "mood_swings",
  "weight_loss",
  "restlessness",
  "lethargy",
  "patches_in_throat",
  "irregular_sugar_level",
  "cough",
  "high_fever",
  "sunken_eyes",
  "breathlessness",
  "sweating",
  "dehydration",
  "indigestion",
  "headache",
  "yellowish_skin",
  "dark_urine",
  "nausea",
  "loss_of_appetite",
  "pain_behind_the_eyes",
  "back_pain",
  "constipation",
  "abdominal_pain",
  "diarrhoea",
  "mild_fever",
  "yellow_urine",
  "yellowing_of_eyes",
  "acute_liver_failure",
  "fluid_overload",
  "swelling_of_stomach",
  "swelled_lymph_nodes",
  "malaise",
  "blurred_and_distorted_vision",
  "phlegm",
  "throat_irritation",
  "redness_of_eyes",
  "sinus_pressure",
  "runny_nose",
  "congestion",
  "chest_pain",
  "weakness_in_limbs",
  "fast_heart_rate",
  "pain_during_bowel_movements",
  "pain_in_anal_region",
  "bloody_stool",
  "irritation_in_anus",
  "neck_pain",
  "dizziness",
  "cramps",
  "bruising",
  "obesity",
  "swollen_legs",
  "swollen_blood_vessels",
  "puffy_face_and_eyes",
  "enlarged_thyroid",
  "brittle_nails",
  "swollen_extremeties",
  "excessive_hunger",
  "extra_marital_contacts",
  "drying_and_tingling_lips",
  "slurred_speech",
  "knee_pain",
  "hip_joint_pain",
  "muscle_weakness",
  "stiff_neck",
  "swelling_joints",
  "movement_stiffness",
  "spinning_movements",
  "loss_of_balance",
  "unsteadiness",
  "weakness_of_one_body_side",
  "loss_of_smell",
  "bladder_discomfort",
  "foul_smell_of",
  "urine",
  "continuous_feel_of_urine",
  "passage_of_gases",
  "internal_itching",
  "toxic_look_(typhos)",
  "depression",
  "irritability",
  "muscle_pain",
  "altered_sensorium",
  "red_spots_over_body",
  "belly_pain",
  "abnormal_menstruation",
  "dischromic",
  "_patches",
  "watering_from_eyes",
  "increased_appetite",
  "polyuria",
  "family_history",
  "mucoid_sputum",
  "rusty_sputum",
  "lack_of_concentration",
  "visual_disturbances",
  "receiving_blood_transfusion",
  "receiving_unsterile_injections",
  "coma",
  "stomach_bleeding",
  "distention_of_abdomen",
  "history_of_alcohol_consumption",
  "fluid_overload",
  "blood_in_sputum",
  "prominent_veins_on_calf",
  "palpitations",
  "painful_walking",
  "pus_filled_pimples",
  "blackheads",
  "scurring",
  "skin_peeling",
  "silver_like_dusting",
  "small_dents_in_nails",
  "inflammatory_nails",
  "blister",
  "red_sore_around_nose",
  "yellow_crust_ooze",
  "prognosis",
];
export const symptoms2 = [
  "mood_swings",
  "weight_loss",
  "restlessness",
  "lethargy",
  "irregular_sugar_level",
  "constipation",
  "fluid_overload",
  "swelled_lymph_nodes",
  "malaise",
  "phlegm",
  "sinus_pressure",
  "obesity",
  "swollen_extremeties",
  "weakness_of_one_body_side",
  "foul_smell_of",
  "internal_itching",
  "toxic_look_(typhos)",
  "depression",
  "irritability",
  "altered_sensorium",
  "dischromic",
  "_patches",
  "polyuria",
  "family_history",
  "mucoid_sputum",
  "rusty_sputum",
  "receiving_blood_transfusion",
  "receiving_unsterile_injections",
  "coma",
  "distention_of_abdomen",
  "fluid_overload",
  "blood_in_sputum",
  "prominent_veins_on_calf",
  "palpitations",
  "pus_filled_pimples",
  "blackheads",
  "scurring",
  "silver_like_dusting",
  "blister",
  "yellow_crust_ooze",
  "prognosis",
  "",
  "nodal_skin_eruptions",
  "shivering",
  "chills",
  "muscle_wasting",
  "burning_micturition",
  "spotting_",
  "fatigue",
  "weight_gain",
  "anxiety",
  "cold_hands_and_feets",
  "high_fever",
  "sweating",
  "dehydration",
  "indigestion",
  "yellowish_skin",
  "nausea",
  "back_pain",
  "abdominal_pain",
  "mild_fever",
  "acute_liver_failure",
  "congestion",
  "fast_heart_rate",
  "bloody_stool",
  "dizziness",
  "cramps",
  "bruising",
  "weakness_in_limbs",
  "swollen_blood_vessels",
  "puffy_face_and_eyes",
  "enlarged_thyroid",
  "excessive_hunger",
  "extra_marital_contacts",
  "hip_joint_pain",
  "muscle_weakness",
  "loss_of_balance",
  "unsteadiness",
];

export const groupsymptoms = {
  anus: { name: "Anus", symptoms: ["stomach_bleeding",
  "passage_of_gases",
  "pain_during_bowel_movements",
  "irritation_in_anus",
  "pain_in_anal_region",
  "movement_stiffness",
  "spinning_movements",
  "diarrhoea",] },
  back: {
    name: "Back",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "red_spots_over_body",
    ],
  },
  breasts: {
    name: "Breasts",
    symptoms: ["itching", "skin_rash", "skin_peeling", "red_spots_over_body"],
  },
  buttocks: {
    name: "Buttocks",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "red_spots_over_body",
      "swelling_joints",
      "joint_pain",
    ],
  },
  chest: {
    name: "Chest",
    symptoms: ["itching", "skin_rash", "skin_peeling", "red_spots_over_body",
    "chest_pain",
    "cough",
    "runny_nose",
    "continuous_sneezing",
    "breathlessness",],
  },
  ears: { name: "Ears", symptoms: ["itching", "skin_rash", "skin_peeling"] },
  elbow: {
    name: "Elbow",
    symptoms: ["itching", "skin_rash", "skin_peeling", "red_spots_over_body",
    "swelling_joints",
    "joint_pain",],
  },
  eyes: {
    name: "Eyes",
    symptoms: [
      "itching",
      "skin_peeling",
      "watering_from_eyes",
      "visual_disturbances",
      "blurred_and_distorted_vision",
      "yellowing_of_eyes",
      "redness_of_eyes",
      "pain_behind_the_eyes",
      "sunken_eyes",
    ],
  },
  foot: {
    name: "Foot",
    symptoms: [
      "itching",
      "skin_rash",
      "inflammatory_nails",
      "small_dents_in_nails",
      "skin_peeling",
      "painful_walking",
      "muscle_pain",
      "red_spots_over_body",
      "swelling_joints",
      "joint_pain",
      "brittle_nails",
      "swollen_legs",
    ],
  },
  forearm: {
    name: "Forearm",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "muscle_pain",
      "red_spots_over_body",
    ],
  },
  hand: {
    name: "Hand",
    symptoms: [
      "itching",
      "skin_rash",
      "inflammatory_nails",
      "small_dents_in_nails",
      "skin_peeling",
      "muscle_pain",
      "red_spots_over_body",
      "swelling_joints",
      "joint_pain",
      "brittle_nails",
    ],
  },
  head: {
    name: "Head",
    symptoms: ["itching", "skin_peeling", "lack_of_concentration",
    "headache",],
  },
  knee: {
    name: "Knee",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "red_spots_over_body",
      "swelling_joints",
      "knee_pain",
      "joint_pain",
      "swollen_legs",
    ],
  },
  lower_abdomen: {
    name: "Lower abdomen",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "history_of_alcohol_consumption",
      "stomach_bleeding",
      "increased_appetite",
      "belly_pain",
      "red_spots_over_body",
      "bladder_discomfort",
      "urine",
      "continuous_feel_of_urine",
      "stomach_pain",
      "acidity",
      "loss_of_appetite",
      "swelling_of_stomach",
      "diarrhoea",
      "urination",
      "dark_urine",
      "yellow_urine",
      "vomiting",
    ],
  },
  lower_back: {
    name: "Lower back",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "red_spots_over_body",
    ],
  },
  lower_leg: {
    name: "Lower leg",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "muscle_pain",
      "red_spots_over_body",
      "swollen_legs",
    ],
  },
  mid_abdomen: {
    name: "Mid abdomen",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "history_of_alcohol_consumption",
      "stomach_bleeding",
      "increased_appetite",
      "belly_pain",
      "red_spots_over_body",
      "stomach_pain",
      "acidity",
      "loss_of_appetite",
      "swelling_of_stomach",
      "diarrhoea",
    ],
  },
  nape_of_neck: {
    name: "Nape of neck",
    symptoms: ["itching", "skin_rash", "skin_peeling", "red_spots_over_body",
    "swelling_joints",
    "stiff_neck",
    "neck_pain",
    "slurred_speech",
    "throat_irritation",
    "patches_in_throat",
    "joint_pain",],
  },
  neck_or_throat: {
    name: "Neck or throat",
    symptoms: ["itching", "skin_peeling", "red_spots_over_body",
    "swelling_joints",
    "stiff_neck",
    "neck_pain",
    "slurred_speech",
    "throat_irritation",
    "patches_in_throat",
    "joint_pain",
    "vomiting",],
  },
  nose: { name: "Nose", symptoms: ["itching", "red_sore_around_nose",
  "cough",
  "runny_nose",
  "continuous_sneezing",
  "loss_of_smell",
  "breathlessness",] },
  oral_cavity: { name: "Oral cavity", symptoms: ["increased_appetite",
  "drying_and_tingling_lips",
  "ulcers_on_tongue",
  "cough",
  "continuous_sneezing",
  "vomiting",] },
  sexual_organs: {
    name: "Sexual organs",
    symptoms: ["itching", "skin_rash", "skin_peeling", "abnormal_menstruation",
    "bladder_discomfort",
    "urine",
    "continuous_feel_of_urine",
    "urination",
    "dark_urine",
    "yellow_urine",],
  },
  thigh: {
    name: "Thigh",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "painful_walking",
      "muscle_pain",
      "red_spots_over_body",
      "joint_pain",
      "swollen_legs",
    ],
  },
  upper_abdomen: {
    name: "Upper abdomen",
    symptoms: ["itching", "skin_rash", "skin_peeling", "red_spots_over_body",
    "chest_pain",
    "breathlessness",],
  },
  upper_arm: {
    name: "Upper arm",
    symptoms: [
      "itching",
      "skin_rash",
      "skin_peeling",
      "muscle_pain",
      "red_spots_over_body",
      "joint_pain",
    ],
  },
  whole_head: {
    name: "Whole head",
    symptoms: ["visual_disturbances", "lack_of_concentration",
    "drying_and_tingling_lips",
    "headache",],
  },
};
